/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'A-4290' at '20/3/16 5:55 PM' with Gradle 2.12
 *
 * @author A-4290, @date 20/3/16 5:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
